ADDITIONAL_COST: 1.88
ANNUAL_USAGE: 1000000
BASELINE_USAGE_MWH: 20000
BATTERY_COST_PER_KWH: 300.0
BATTERY_INEFFICIENCY_FACTOR: 0.95
BATTERY_POWER: 50
BATTERY_SIZE_KWH: 100
CHP_SURCHARGE: 0.45
ELECTRICITY_TAX: 2.05
FLAT_RATE_C_PER_KWH: 30.0
INFLATION_RATE: 0.02
KONZESSION: 1.66
NETWORK_USAGE: 8.71
OPEX_PERCENT_OF_CAPEX: 0.05
SOC_FACTOR: 0.8
TAX_RATE: 0.19
